apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.named-data.net
spec:
  group: named-data.net
  names:
    categories: []
    kind: Certificate
    plural: certificates
    shortNames:
    - cert
    singular: certificate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.prefix
      name: Prefix
      type: string
    - jsonPath: .status.key.name
      name: Key
      type: string
    - jsonPath: .status.cert.name
      name: Cert
      type: string
    - jsonPath: .status.cert.valid
      name: Valid
      type: boolean
    - jsonPath: .status.keyExists
      name: Key Exists
      type: boolean
    - jsonPath: .status.certExists
      name: Cert Exists
      type: boolean
    - jsonPath: .status.needsRenewal
      name: Needs Renewal
      type: boolean
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Certificate is a custom resource for managing NDN certificates
        properties:
          spec:
            properties:
              issuer:
                description: |-
                  The issuer of the certificate, which can be another Certificate or an external issuer.
                  Can reference itself if the certificate is self-signed
                properties:
                  kind:
                    description: |-
                      The kind of the issuer, e.g., "Certificate".
                      Currently only "Certificate" is supported
                    type: string
                  name:
                    description: The name of the issuer, e.g., "router-cert"
                    type: string
                  namespace:
                    description: |-
                      The namespace of the issuer
                      If not specified, the certificate's namespace will be used
                    nullable: true
                    type: string
                required:
                - kind
                - name
                type: object
              prefix:
                description: The prefix for the certificate, used for routing and naming conventions
                type: string
              renewBefore:
                description: |-
                  When the certificate should be renewed before it expires.
                  This is a duration string, e.g., "7d2h" for 7 days and 2 hours.
                  If not specified, defaults to 24 hours
                nullable: true
                type: string
              renewInterval:
                description: Duration of the certificate validity (total lifetime)
                nullable: true
                type: string
            required:
            - issuer
            - prefix
            type: object
          status:
            nullable: true
            properties:
              cert:
                description: The status of the certificate file
                properties:
                  issuedAt:
                    description: The time when the certificate was issued (RFC3339)
                    nullable: true
                    type: string
                  name:
                    description: The parsed full NDN name of the certificate
                    nullable: true
                    type: string
                  secret:
                    description: The name of the Secret that contains the certificate data (and signer cert)
                    nullable: true
                    type: string
                  sigType:
                    description: The signature type of the certificate, e.g., "ECDSA"
                    nullable: true
                    type: string
                  signerKey:
                    description: The name of the signer key used to sign the certificate
                    nullable: true
                    type: string
                  valid:
                    description: Indicates whether the certificate is currently valid (not expired)
                    type: boolean
                  validUntil:
                    description: The time when the certificate is valid until (RFC3339)
                    nullable: true
                    type: string
                required:
                - valid
                type: object
              certExists:
                description: Indicates whether the cert exists
                type: boolean
              conditions:
                description: |-
                  Standard Kubernetes-style conditions for this certificate
                  - Ready: key and cert are present and cert is valid
                  - IssuerReady: issuer is resolved and usable (best-effort)
                  - KeyReady: key secret available/usable (proxy by key_exists)
                  - CertReady: cert available and valid
                  - RenewalRequired: within renew window
                  - Issuing: an issuance/renewal is in progress
                items:
                  description: Condition contains details for one aspect of the current state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating details about the transition. This may be an empty string.
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty.
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                nullable: true
                type: array
              key:
                description: The status of the certificate key
                properties:
                  name:
                    description: The parsed full NDN name of the key
                    nullable: true
                    type: string
                  secret:
                    description: The name of the Secret that contains the key data
                    nullable: true
                    type: string
                  sigType:
                    description: The signature type of the key, e.g., "ECDSA"
                    nullable: true
                    type: string
                type: object
              keyExists:
                description: Indicates whether the key exists
                type: boolean
              needsRenewal:
                description: Indicates whether the certificate needs renewal
                type: boolean
            required:
            - cert
            - certExists
            - key
            - keyExists
            - needsRenewal
            type: object
        required:
        - spec
        title: Certificate
        type: object
    served: true
    storage: true
    subresources:
      status: {}
