apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalcertificates.named-data.net
spec:
  group: named-data.net
  names:
    categories: []
    kind: ExternalCertificate
    plural: externalcertificates
    shortNames:
    - ecert
    singular: externalcertificate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.secretName
      name: Secret
      type: string
    - jsonPath: .status.cert.name
      name: Cert
      type: string
    - jsonPath: .status.cert.valid
      name: Valid
      type: boolean
    - jsonPath: .status.keyExists
      name: Key Exists
      type: boolean
    - jsonPath: .status.certExists
      name: Cert Exists
      type: boolean
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ExternalCertificate imports an existing NDN certificate from a Kubernetes Secret
        properties:
          spec:
            description: ExternalCertificate is a custom resource representing a pre-generated certificate imported via a Secret
            properties:
              secretName:
                description: |-
                  The name of the Secret containing the external certificate (and optionally key)
                  The Secret must contain `ndn.cert` and may contain `ndn.key`
                type: string
            required:
            - secretName
            type: object
          status:
            nullable: true
            properties:
              cert:
                description: The status of the certificate file
                properties:
                  issuedAt:
                    description: The time when the certificate was issued (RFC3339)
                    nullable: true
                    type: string
                  name:
                    description: The parsed full NDN name of the certificate
                    nullable: true
                    type: string
                  secret:
                    description: The name of the Secret that contains the certificate data (and signer cert)
                    nullable: true
                    type: string
                  sigType:
                    description: The signature type of the certificate, e.g., "ECDSA"
                    nullable: true
                    type: string
                  signerKey:
                    description: The name of the signer key used to sign the certificate
                    nullable: true
                    type: string
                  valid:
                    description: Indicates whether the certificate is currently valid (not expired)
                    type: boolean
                  validUntil:
                    description: The time when the certificate is valid until (RFC3339)
                    nullable: true
                    type: string
                required:
                - valid
                type: object
              certExists:
                description: Indicates whether the cert exists in the referenced Secret
                type: boolean
              conditions:
                description: |-
                  Standard Kubernetes-style conditions for this external certificate
                  - Ready: key and cert are present and cert is valid
                  - KeyReady: key secret available/usable (proxy by key_exists)
                  - CertReady: cert available and valid
                items:
                  description: Condition contains details for one aspect of the current state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating details about the transition. This may be an empty string.
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty.
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                nullable: true
                type: array
              key:
                description: The status of the certificate key (if provided)
                properties:
                  name:
                    description: The parsed full NDN name of the key
                    nullable: true
                    type: string
                  secret:
                    description: The name of the Secret that contains the key data
                    nullable: true
                    type: string
                  sigType:
                    description: The signature type of the key, e.g., "ECDSA"
                    nullable: true
                    type: string
                type: object
              keyExists:
                description: Indicates whether the key exists in the referenced Secret
                type: boolean
            required:
            - cert
            - certExists
            - key
            - keyExists
            type: object
        required:
        - spec
        title: ExternalCertificate
        type: object
    served: true
    storage: true
    subresources:
      status: {}
