apiVersion: named-data.net/v1alpha1
kind: Certificate
metadata:
  name: test1-root
  namespace: mynetwork
spec:
  prefix: /test1
  issuer:
    name: test1-root
    kind: Certificate
  renewBefore: 23h50m
  renewInterval: 4d15h
