apiVersion: named-data.net/v1alpha1
kind: Certificate
metadata:
  name: app-root
spec:
  prefix: /root-network
  issuer:
    name: app-root
    kind: Certificate
  renewBefore: 23h50m
  renewInterval: 4d15h
---
apiVersion: named-data.net/v1alpha1
kind: Certificate
metadata:
  name: app-subnetwork1-ca
spec:
  prefix: /root-network/subnetwork1
  issuer:
    name: app-root
    kind: Certificate
  renewBefore: 23h50m
  renewInterval: 4d15h
---
apiVersion: named-data.net/v1alpha1
kind: Certificate
metadata:
  name: app-subnetwork1-helloworld
spec:
  prefix: /root-network/subnetwork1/helloworld
  issuer:
    name: app-subnetwork1-ca
    kind: Certificate
  renewBefore: 23h50m
  renewInterval: 4d15h
---
apiVersion: named-data.net/v1alpha1
kind: Certificate
metadata:
  name: app-subnetwork2-ca
spec:
  prefix: /root-network/subnetwork2
  issuer:
    name: app-root
    kind: Certificate
  renewBefore: 23h50m
  renewInterval: 4d15h
---
apiVersion: named-data.net/v1alpha1
kind: Certificate
metadata:
  name: app-subnetwork2-helloworld
spec:
  prefix: /root-network/subnetwork2/helloworld
  issuer:
    name: app-subnetwork2-ca
    kind: Certificate
  renewBefore: 23h50m
  renewInterval: 4d15h
