apiVersion: batch/v1
kind: Job
metadata:
  name: test-helloworld-consumer
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
        networks.named-data.net/name: test
        networks.named-data.net/namespace: mynetwork
        credentials.named-data.net/container: consumer
        credentials.named-data.net/trust-anchors: Certificate/app-root
        credentials.named-data.net/certificate-chain: Certificate/app-subnetwork1-ca,Certificate/app-subnetwork1-helloworld
      labels:
        named-data.net/inject: "true"
    spec:
      restartPolicy: Never
      tolerations:
      - key: kubernetes.io/arch
        operator: Equal
        value: arm64
        effect: NoSchedule
      containers:
      - name: consumer
        image: ghcr.io/ndn-operator/ndn-helloworld-rs:latest
        command: ["/consumer"]
        args: ["--name", "/root-network/subnetwork1/helloworld/valid"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
