apiVersion: v1
kind: Secret
metadata:
  name: mynetwork-cert
  namespace: mynetwork
type: Opaque
stringData:
  ndn.cert: |
    -----BEGIN NDN CERT-----
    Name: /mynetwork/KEY/M%CE%1B5%C4%84%21%AE/NA/v=1757890242315
    SigType: Sha256WithEcdsa
    SignerKey: /root/KEY/W%B4L%3F%87v%1B2
    Validity: 2025-09-14 22:50:42 +0000 UTC - 2026-09-14 22:50:42 +0000 UTC

    Bv0BJAcoCAlteW5ldHdvcmsIA0tFWQgITc4bNcSEIa4IAk5BNggAAAGZSmxnCxQJ
    GAECGQQANu6AFVswWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATa1eAX0/gFJdUJ
    BZlpyMwBhN1ozb8bVsqIbqEWIXmQNXBtxm2kiQkZN0Dj9t1lGpBVz2XHEvn1ICKb
    pQsniwRqFkYbAQMcFwcVCARyb290CANLRVkICFe0TD+Hdhsy/QD9Jv0A/g8yMDI1
    MDkxNFQyMjUwNDL9AP8PMjAyNjA5MTRUMjI1MDQyF0gwRgIhAOOBdP5CtGZqj7V8
    1gSJZBzSpnA7LQRugHqIXxzdfp6OAiEAmfe4AcrsvtCVavG2ejD4bBGvkgFBWwSN
    vm6w1bfj4Js=
    -----END NDN CERT-----
  ndn.key: |
    -----BEGIN NDN KEY-----
    Name: /mynetwork/KEY/M%CE%1B5%C4%84%21%AE
    SigType: Sha256WithEcdsa

    Bv0BCQcaCAlteW5ldHdvcmsIA0tFWQgITc4bNcSEIa4UAxgBCRV5MHcCAQEEIMqo
    JcwGXCRf1mK8Qma/S/dlSBrbgLmfqnQC/bQNzq2doAoGCCqGSM49AwEHoUQDQgAE
    2tXgF9P4BSXVCQWZacjMAYTdaM2/G1bKiG6hFiF5kDVwbcZtpIkJGTdA4/bdZRqQ
    Vc9lxxL59SAim6ULJ4sEahYhGwEDHBwHGggJbXluZXR3b3JrCANLRVkICE3OGzXE
    hCGuF0gwRgIhAJW9QZ5J0K4YWlsfzk8K9tBiM+HTrbQu/AWObp80uMsTAiEAvAw8
    oS4F65vitybxOJ2ZlV6+Tebq21uv9iEzGOk6HiQ=
    -----END NDN KEY-----
