apiVersion: named-data.net/v1alpha1
kind: Network
metadata:
  name: test
  namespace: mynetwork
spec:
  prefix: /test
  udpUnicastPort: 6363
  ndnd:
    image: ghcr.io/named-data/ndnd:1.5.2
  operator:
    image: ghcr.io/ndn-operator/ndn-operator:sha-12f4e3b
  routerCertIssuer:
    kind: Certificate
    name: self-signed
  trustAnchors:
  - name: self-signed
    kind: Certificate
  faces:
    tcp:
      port: 6364
