apiVersion: named-data.net/v1alpha1
kind: Network
metadata:
  name: test
  namespace: mynetwork
spec:
  prefix: /root-network/subnetwork1
  dvNetwork: /root-network
  udpUnicastPort: 6363
  ndnd:
    image: ghcr.io/named-data/ndnd:1.5.2
  operator:
    image: ghcr.io/ndn-operator/ndn-operator:latest
  template:
    tolerations:
    - key: kubernetes.io/arch
      operator: Equal
      value: arm64
      effect: NoSchedule
  routerCertIssuer:
    kind: Certificate
    name: self-signed
  trustAnchors:
  - name: self-signed
    kind: Certificate
